{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bizdash.serviceAccountName" . }}
  labels:
{{ include "bizdash.labels" . | nindent 4 }}
{{- end -}}
