apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: {{.Values.scale}}
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx:{{.Values.nginx-version}}
              ports:
              - containerPort: 80
 