apiVersion: v1
kind: Service
metadata:
  name: {{ include "bizdash.fullname" . }}
  labels:
    {{- include "bizdash.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "bizdash.selectorLabels" . | nindent 4 }}
