apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bizdash-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: bizdash-ip-address
    networking.gke.io/managed-certificates: bizdash-cert
spec:
  backend:
    serviceName: example-nodeport-service
    servicePort: 80
