apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    name: influxdb
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: influxdb-pod
  labels:
    name: busybox
spec:
  hostname: influxdb-pod
  subdomain: default-subdomain
  containers:
  - image: docker.io/influxdb:1.6.4
    command:
      - sleep
      - "3600"
    name: busybox
