apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-02-06T03:33:35Z"
  name: bizdash.dizzastuh.page
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://dizzastuh-kube-clusters/bizdash.dizzastuh.page
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west1-a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west1-a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.7
  masterPublicName: api.bizdash.dizzastuh.page
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: bizdash
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-west1
    region: us-west1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-06T03:33:36Z"
  labels:
    kops.k8s.io/cluster: bizdash.dizzastuh.page
  name: master-us-west1-a
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-1
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west1-a
  role: Master
  subnets:
  - us-west1
  zones:
  - us-west1-a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-06T03:33:37Z"
  labels:
    kops.k8s.io/cluster: bizdash.dizzastuh.page
  name: nodes
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-2
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west1
  zones:
  - us-west1-a
